language: node_js
node_js:
- 5.4.1
cache:
  directories:
  - node_modules
env:
  global:
  - secure: PUrT7OMqEtO1F1CfkNyWMd6Xyqn5XLSD/LgA5wRCotuFDh9gCXCVuNWzzcsHK5tDIgiNKnuUTJCltvbLLMyqGQlf2II2C4fyGG5ij70z8GPUhkFZjjARIqZWhcvOi0n9Fe1BkpIUuDuQ0Jc8HXyyNle+MswxEa5KS7TbBM5egUgEVyTxHxtX6hTFp67FozorK6tdHWWsfl89LyrHwrYs9Nz/uuEOrRWjQKY0aYjInLVpfL6zAAgGfR2Xn2VSfIWS1XEzxBswSurJ+bhl6ZoHFYnYU6ojri4LBXeCyRB1L0ApZ4lNCq3Iw8rhddEUwVFoVEVHPLdHi2dAq0nqgO8r9rDMYd10pnnHlV0JZfcdhDPPdiwPZoPM8hyyte1Ul9JLCwUHETkGLgo4B0TCvu0OR2dPtTxwv3QskjyYMg/7EEUtUk1Jg0sMfDQ3xN23Iu/NNwQkPpW2RjMs9aiE7pndQ8fia1eqE0lEc2NgvipdQDI+p1mJGSnTTFrcaFx3yTPi1753mThQPxUIQYu1qJ2DtFX3yMH6nyW/FGtZX5augMR2D2HZ77rG9BYRoEWT2LeWKQrh8xrgb2zPvVNajNDZVE41w2KyUxf6SyMH22b0LwBCrWlnkp8b1FbmKJGcYKVp+Hex+zfPZzCXhASr/H9DUcKNlnBUThk7ZYRLVMclzdU=
  - secure: 4ERhnZJjlDOIJe2PX6xeEeeJZXknhg9DpOWNxMv/U5FLvT0FNSLxyZvYPGGOR+IjrbTBhuC0znoQf2OG9u1Z7FMAAttIR+GqpzQQMij5ApxuL0y7Am9CnQvEwdgdIUuWGYO3KxOLk+1Fk2LHpiEZ4xoPWjerjVQKrqW7gOMEvDjeO7C9e80za+9ODFuXrH4a5jh2WrNBoPpz+zKOLswQws+wQuCG/6IO6lLYlfXi7Uh9uEyVP6Rs/8YtR92C/m8c1HCyfCUB2v6Gp5ckXN2+WcjVktTKNttj6ZYqeFzkIOENjJ46IrPGprqovbJGS+3ijxnIsJm2koICjF2yu3onUbQFu+gVUdmA9PriyVtSCa/GGxr3Oj8rDTxmJACrXYI3giODrvTIQ3bohZmBWIdAj8VQ10vxYsvipj9qg1EgiS5VDmS1VdNJJKX75GOurW9d9td38pB0maXV8PthPEw5BqltARWNZgYT335vTioCuNsAIKGaGUDehiFUTjCz/12pIx4pUsIWaULs3CL1+d66yQaiR6s3Q9p8WY9TDKlSLKJemPtEvonBhK99uk+bKSA5RBNNgxY4LvhLOe348drJjL8RnddYyDK6/jxH2WPdc7+4xwrb0piPb3oLObx3WVO7pJl9e+zON9BrINTbwVQFdgheQJWLqMO+iS3e8xoGR34=
before_script:
- npm install -g bower
- npm install -g gulp
- npm install
- bower install
- gulp build:prod
after_success:
  gulp deploy --user $FTP_USER --password $FTP_PASSWORD

